POST  http://localhost:4002/products
Content-Type: application/json

{
    "name": "dasda asdsa azul",
    "price": 44
}
###

GET http://localhost:4002/products
###

GET http://localhost:4002/products/acbc992e-72a1-48bc-b195-e699ca6cdecd
###

PUT  http://localhost:4002/products/c58e6daf-7dfe-4453-822c-8e1e4c6a16e5
Content-Type: application/json

{
    "name": "casasdas azul",
    "price": 99
}
###

DELETE http://localhost:4002/products/0c71e47f-a86e-460f-bdf8-6e82cae60d1f